/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.AuthorController;
import Controller.CategoryController;
import Controller.koneksi;
import Model.AuthorTableModel;
import java.sql.*;
import dynamic_subjtable.TableCustom;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author kahfi
 */
public class DashboardView extends javax.swing.JFrame {
    
    AuthorController authorController; 
    CategoryController categoryController; 

    public DashboardView() {
        initComponents();
        this.authorController = new AuthorController(this); 
        this.categoryController = new CategoryController(this);
        loadAuthorData();
        loadCategoryData();
      
  

    }

    public TableCustom getAuthorTable() {
        return authorTable;
    }
    
    public void loadAuthorData()
    {
        authorController.loadData();
    }
    
    public void loadCategoryData()
    {
        categoryController.loadData();
    }

    private void setActiveButton(View.Button activeButton) {

        // Mengatur warna tombol-tombol
        dashboardButton.setBackground(activeButton == dashboardButton ? new Color(153, 153, 255) : new Color(255, 255, 255));
        jurnalButton.setBackground(activeButton == jurnalButton ? new Color(153, 153, 255) : new Color(255, 255, 255));
        categoryButton.setBackground(activeButton == categoryButton ? new Color(153, 153, 255) : new Color(255, 255, 255));
        authorButton.setBackground(activeButton == authorButton ? new Color(153, 153, 255) : new Color(255, 255, 255));
        settingButton.setBackground(activeButton == settingButton ? new Color(153, 153, 255) : new Color(255, 255, 255));
    }
    
     public void setActivePanel(JPanel activePanel) {
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        // add new panel
        mainPanel.add(activePanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SidePanel = new javax.swing.JPanel();
        dashboardButton = new View.Button();
        jurnalButton = new View.Button();
        categoryButton = new View.Button();
        settingButton = new View.Button();
        authorButton = new View.Button();
        mainPanel = new javax.swing.JPanel();
        dashboardPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jurnalPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        categoryPanel = new javax.swing.JPanel();
        categoryScrollPanel = new javax.swing.JScrollPane();
        categoryTable = new dynamic_subjtable.TableCustom();
        authorPanel = new javax.swing.JPanel();
        authorScrollPane = new javax.swing.JScrollPane();
        authorTable = new dynamic_subjtable.TableCustom();
        newAuthorButton = new View.Button();
        fieldSearchAuthor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        settingPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        CreateAuthorPanel = new javax.swing.JPanel();
        panelRound1 = new View.PanelRound();
        jLabel7 = new javax.swing.JLabel();
        fieldName = new textfield.TextField();
        fieldAddress = new textfield.TextField();
        fieldContact = new textfield.TextField();
        authorOperationButton = new View.Button();
        authorOperationCancel = new View.Button();
        authorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SidePanel.setBackground(new java.awt.Color(255, 255, 255));
        SidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboardButton.setBackground(new java.awt.Color(153, 153, 255));
        dashboardButton.setForeground(new java.awt.Color(0, 0, 0));
        dashboardButton.setText("   Home");
        dashboardButton.setSelected(true);
        dashboardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardButtonMouseClicked(evt);
            }
        });
        dashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardButtonActionPerformed(evt);
            }
        });
        SidePanel.add(dashboardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 155, 160, -1));

        jurnalButton.setForeground(new java.awt.Color(0, 0, 0));
        jurnalButton.setText("  Journals");
        jurnalButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jurnalButtonMouseClicked(evt);
            }
        });
        jurnalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jurnalButtonActionPerformed(evt);
            }
        });
        SidePanel.add(jurnalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 210, 140, -1));

        categoryButton.setForeground(new java.awt.Color(0, 0, 0));
        categoryButton.setText("  Category");
        categoryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoryButtonMouseClicked(evt);
            }
        });
        categoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryButtonActionPerformed(evt);
            }
        });
        SidePanel.add(categoryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 265, 140, -1));

        settingButton.setForeground(new java.awt.Color(0, 0, 0));
        settingButton.setText(" Settings");
        settingButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingButtonMouseClicked(evt);
            }
        });
        settingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingButtonActionPerformed(evt);
            }
        });
        SidePanel.add(settingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 150, -1));

        authorButton.setForeground(new java.awt.Color(0, 0, 0));
        authorButton.setText("  Authors");
        authorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                authorButtonMouseClicked(evt);
            }
        });
        authorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorButtonActionPerformed(evt);
            }
        });
        SidePanel.add(authorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 150, -1));

        jPanel1.add(SidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 600));

        mainPanel.setLayout(new java.awt.CardLayout());

        jLabel1.setText("Dashboard");

        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addGap(0, 374, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 374, Short.MAX_VALUE))
        );
        dashboardPanelLayout.setVerticalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addGap(0, 291, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 291, Short.MAX_VALUE))
        );

        mainPanel.add(dashboardPanel, "card2");

        jLabel2.setText("Journal");

        javax.swing.GroupLayout jurnalPanelLayout = new javax.swing.GroupLayout(jurnalPanel);
        jurnalPanel.setLayout(jurnalPanelLayout);
        jurnalPanelLayout.setHorizontalGroup(
            jurnalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jurnalPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jurnalPanelLayout.setVerticalGroup(
            jurnalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jurnalPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mainPanel.add(jurnalPanel, "card3");

        categoryPanel.setBackground(new java.awt.Color(255, 255, 255));

        categoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        categoryScrollPanel.setViewportView(categoryTable);

        javax.swing.GroupLayout categoryPanelLayout = new javax.swing.GroupLayout(categoryPanel);
        categoryPanel.setLayout(categoryPanelLayout);
        categoryPanelLayout.setHorizontalGroup(
            categoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, categoryPanelLayout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(categoryScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        categoryPanelLayout.setVerticalGroup(
            categoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, categoryPanelLayout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addComponent(categoryScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        mainPanel.add(categoryPanel, "card4");

        authorPanel.setBackground(new java.awt.Color(255, 255, 255));
        authorPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        authorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        authorTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                authorTableMouseClicked(evt);
            }
        });
        authorTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                authorTableKeyReleased(evt);
            }
        });
        authorScrollPane.setViewportView(authorTable);

        authorPanel.add(authorScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 159, 750, 380));

        newAuthorButton.setBackground(new java.awt.Color(153, 153, 255));
        newAuthorButton.setText("New Author");
        newAuthorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAuthorButtonActionPerformed(evt);
            }
        });
        authorPanel.add(newAuthorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, -1, -1));

        fieldSearchAuthor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fieldSearchAuthor.setSelectionColor(new java.awt.Color(255, 255, 255));
        fieldSearchAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldSearchAuthorActionPerformed(evt);
            }
        });
        fieldSearchAuthor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldSearchAuthorKeyReleased(evt);
            }
        });
        authorPanel.add(fieldSearchAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 190, 30));

        jLabel4.setText("Search Author");
        authorPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 20));

        mainPanel.add(authorPanel, "card5");

        jLabel5.setText("Setting");

        javax.swing.GroupLayout settingPanelLayout = new javax.swing.GroupLayout(settingPanel);
        settingPanel.setLayout(settingPanelLayout);
        settingPanelLayout.setHorizontalGroup(
            settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
            .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(settingPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        settingPanelLayout.setVerticalGroup(
            settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(settingPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        mainPanel.add(settingPanel, "card6");

        CreateAuthorPanel.setBackground(new java.awt.Color(255, 255, 255));
        CreateAuthorPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelRound1.setRoundBottomLeft(10);
        panelRound1.setRoundBottomRight(10);
        panelRound1.setRoundTopLeft(10);
        panelRound1.setRoundTopRight(10);

        fieldName.setLabelText("Name");
        fieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNameActionPerformed(evt);
            }
        });

        fieldAddress.setLabelText("Address");
        fieldAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAddressActionPerformed(evt);
            }
        });

        fieldContact.setLabelText("Contact");
        fieldContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldContactActionPerformed(evt);
            }
        });

        authorOperationButton.setBackground(new java.awt.Color(153, 153, 255));
        authorOperationButton.setText("Create");
        authorOperationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorOperationButtonActionPerformed(evt);
            }
        });

        authorOperationCancel.setBackground(new java.awt.Color(204, 204, 204));
        authorOperationCancel.setText("Cancel");
        authorOperationCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorOperationCancelActionPerformed(evt);
            }
        });

        authorLabel.setForeground(new java.awt.Color(102, 102, 102));
        authorLabel.setText("Create Author");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(authorLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRound1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel7))
                            .addGroup(panelRound1Layout.createSequentialGroup()
                                .addComponent(authorOperationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(authorOperationCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldContact, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65))))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authorLabel)
                .addGap(18, 18, 18)
                .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(fieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fieldContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(authorOperationButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(authorOperationCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        CreateAuthorPanel.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 400, 460));

        mainPanel.add(CreateAuthorPanel, "card7");

        jPanel1.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 810, 600));

        getContentPane().add(jPanel1, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardButtonActionPerformed
        setActiveButton(dashboardButton);
        setActivePanel(dashboardPanel);
    }//GEN-LAST:event_dashboardButtonActionPerformed

    private void jurnalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jurnalButtonActionPerformed
        setActiveButton(jurnalButton);
        setActivePanel(jurnalPanel);
    }//GEN-LAST:event_jurnalButtonActionPerformed

    private void categoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryButtonActionPerformed
        setActiveButton(categoryButton);    
        setActivePanel(categoryPanel);
    }//GEN-LAST:event_categoryButtonActionPerformed

    private void settingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingButtonActionPerformed
        setActiveButton(settingButton);
        setActivePanel(settingPanel);

    }//GEN-LAST:event_settingButtonActionPerformed

    private void authorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorButtonActionPerformed
        setActiveButton(authorButton);
        setActivePanel(authorPanel);

    }//GEN-LAST:event_authorButtonActionPerformed

    private void dashboardButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardButtonMouseClicked



    }//GEN-LAST:event_dashboardButtonMouseClicked

    private void jurnalButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jurnalButtonMouseClicked


    }//GEN-LAST:event_jurnalButtonMouseClicked

    private void categoryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryButtonMouseClicked
   

    }//GEN-LAST:event_categoryButtonMouseClicked

    private void authorButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_authorButtonMouseClicked

    }//GEN-LAST:event_authorButtonMouseClicked

    private void settingButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingButtonMouseClicked

    }//GEN-LAST:event_settingButtonMouseClicked

    private void newAuthorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAuthorButtonActionPerformed

        authorController.insertOperation();
    }//GEN-LAST:event_newAuthorButtonActionPerformed

    private void fieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNameActionPerformed

    private void fieldAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAddressActionPerformed

    private void fieldContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldContactActionPerformed

    private void authorOperationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorOperationButtonActionPerformed
        authorController.doOperation();
    }//GEN-LAST:event_authorOperationButtonActionPerformed

    private void authorOperationCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorOperationCancelActionPerformed
        authorController.doOperationCancel();
    }//GEN-LAST:event_authorOperationCancelActionPerformed

    private void authorTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_authorTableMouseClicked
         authorController.fillData();
    }//GEN-LAST:event_authorTableMouseClicked

    private void authorTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_authorTableKeyReleased
       
    }//GEN-LAST:event_authorTableKeyReleased

    private void fieldSearchAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldSearchAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldSearchAuthorActionPerformed

    private void fieldSearchAuthorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldSearchAuthorKeyReleased
       authorController.loadData();
    }//GEN-LAST:event_fieldSearchAuthorKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel CreateAuthorPanel;
    private javax.swing.JPanel SidePanel;
    private View.Button authorButton;
    public javax.swing.JLabel authorLabel;
    public View.Button authorOperationButton;
    public View.Button authorOperationCancel;
    public javax.swing.JPanel authorPanel;
    public static javax.swing.JScrollPane authorScrollPane;
    public dynamic_subjtable.TableCustom authorTable;
    private View.Button categoryButton;
    private javax.swing.JPanel categoryPanel;
    public javax.swing.JScrollPane categoryScrollPanel;
    public dynamic_subjtable.TableCustom categoryTable;
    private View.Button dashboardButton;
    private javax.swing.JPanel dashboardPanel;
    public textfield.TextField fieldAddress;
    public textfield.TextField fieldContact;
    public textfield.TextField fieldName;
    public javax.swing.JTextField fieldSearchAuthor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private View.Button jurnalButton;
    private javax.swing.JPanel jurnalPanel;
    private javax.swing.JPanel mainPanel;
    public View.Button newAuthorButton;
    private View.PanelRound panelRound1;
    private View.Button settingButton;
    private javax.swing.JPanel settingPanel;
    // End of variables declaration//GEN-END:variables


}
